version: "3.8"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    networks:
      springboot-mysql-net:

  app:
    container_name: restapi-v4
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:

#after pushing image to docker hub repository remove the build parameter under app service then add "image: shivangimittal791/rest-api" similar to mysql service